name: Build
on:
  workflow_dispatch:

jobs:
  windowsAmd64Build:
    name: Build Windows amd64 Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Building Windows amd64 Version
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o WireProxy_amd64.exe -v main.go
          mkdir release_windows_amd64
          mv WireProxy_amd64.exe wireproxy.exe
          cp wireproxy.exe release_windows_amd64/wireproxy.exe
      - name: Upload Windows amd64 Version
        uses: actions/upload-artifact@v1
        with:
          name: WireProxy_windows_amd64
          path: release_windows_amd64
